faiss_db:
  collection_name: "document_portal"

embedding_model:
  provider_name: "openai"
  model_name: "text-embedding-small-3"

retriever:
  top_k: 10 

llm:
  gpt4o_mini:
    provider_name: "openai"
    model_name: "gpt-4o-mini"
    temperature: 0
    max_output_tokens: 2048
